version: '3'
services:
  project:
    image: lts_filter
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ipc: host
    privileged: true
    volumes:
      - ${PWD}/:/lts
      - ${DATA}:/lts/data
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_MASTER_URI=$ROS_MASTER_URI
    working_dir: /lts

